export const SET_PLATE_IMAGE_URL = 'SET_PLATE_IMAGE_URL';
export const REQUEST_UPDATE_RULE = 'REQUEST_UPDATE_RULE';
export const UPDATE_RULE_SUCESS = 'UPDATE_RULE_SUCESS';
export const UPDATE_RULE_FAILURE = 'UPDATE_RULE_FAILURE';
export const REQUEST_ADD_RULE = 'REQUEST_ADD_RULE';
export const ADD_RULE_SUCESS = 'ADD_RULE_SUCESS';
export const ADD_RULE_FAILURE = 'ADD_RULE_FAILURE';
export const SET_CURRENT_PLATE = 'SET_CURRENT_PLATE';
