export const REQUEST_EXPERIMENT_IMAGES = 'REQUEST_EXPERIMENT_IMAGES';
export const RECEIVED_EXPERIMENT_IMAGES = 'RECEIVED_EXPERIMENT_IMAGES';
export const EXPERIMENT_IMAGES_FAILURE = 'EXPERIMENT_IMAGES_FAILURE';
