# Generated by Django 2.0.2 on 2018-03-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RulesScriptModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='experimentmodel',
            name='rules_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_rule_script', to='app.RulesScriptModel'),
        ),
    ]
