# Generated by Django 2.0 on 2018-05-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabChipResults',
            new_name='LabChipResultsModel',
        ),
    ]
