# Generated by Django 2.0 on 2017-12-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('abbreviation', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
