# Generated by Django 2.0 on 2018-05-21 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentgroupdetailsmodel',
            name='reagent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='app.ReagentGroupModel'),
        ),
    ]
