# Generated by Django 2.0 on 2017-12-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='direction',
            field=models.CharField(choices=[('FWD', 'Forward'), ('REV', 'Reverse')], default='FWD', max_length=7),
            preserve_default=False,
        ),
    ]
