# Generated by Django 2.0 on 2018-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labchipresultsmodel',
            name='molarity',
        ),
        migrations.AddField(
            model_name='labchipresultsmodel',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='labchipresultsmodel',
            name='exclude_well',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qpcrresultsmodel',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qpcrresultsmodel',
            name='exclude_well',
            field=models.BooleanField(default=False),
        ),
    ]
