# Generated by Django 2.0 on 2018-05-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180521_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='labchipresultsmodel',
            name='purity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reagentgroupdetailsmodel',
            name='reagent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.ReagentGroupModel'),
        ),
    ]
