# Generated by Django 2.0 on 2017-12-17 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_primer_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PA', 'Pre-Amp'), ('ID', 'Identification')], max_length=2)),
                ('fwd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_fwd', to='app.Primer')),
                ('rev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_rev', to='app.Primer')),
            ],
        ),
    ]
