# Generated by Django 2.0 on 2017-12-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_organism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arg',
            fields=[
                ('name', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
