# Generated by Django 2.0 on 2017-12-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_arg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('genome_size', models.BigIntegerField()),
                ('arg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Arg', to='app.Arg')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strain', to='app.Organism')),
            ],
        ),
    ]
