# Generated by Django 2.0 on 2018-05-25 10:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_experimentmodel_experiment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentmodel',
            name='opaque_json_payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
