# Generated by Django 2.0 on 2018-05-25 10:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180525_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentmodel',
            name='opaque_json_payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
