# Generated by Django 2.0 on 2017-12-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_cyclingpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentration',
            fields=[
                ('string_code', models.CharField(editable=False, max_length=80, primary_key=True, serialize=False, unique=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('units', models.CharField(choices=[('X', 'X'), ('mM', 'mM'), ('mg/ml', 'mg/ml'), ('mM each', 'mM each'), ('microM each', 'microM each'), ('ng/ul', 'ng/ul'), ('cp/ul', 'cp/ul'), ('%', '%')], max_length=15)),
            ],
        ),
    ]
