# Generated by Django 2.0 on 2017-12-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentration',
            name='final',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='concentration',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
