# Generated by Django 2.0 on 2018-05-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180525_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reagentmodel',
            name='opaque_json_payload',
            field=models.TextField(null=True),
        ),
    ]
