# Generated by Django 2.0 on 2017-12-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171219_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentration',
            name='string_code',
            field=models.CharField(editable=False, max_length=80, primary_key=True, serialize=False),
        ),
    ]
