# Generated by Django 2.0 on 2017-12-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171219_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentration',
            name='string_code',
            field=models.CharField(editable=False, max_length=80, primary_key=True, serialize=False, unique=True),
        ),
    ]
