# Generated by Django 2.0 on 2017-12-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171219_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentration',
            name='string_code',
        ),
        migrations.AddField(
            model_name='concentration',
            name='id',
            field=models.AutoField(auto_created=True, default=42, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
