export const SET_TEMPLATE_RULES = 'SET_TEMPLATE_RULES';
export const SET_HGDNA_RULES = 'SET_HGDNA_RULES';
export const SET_DILUTION_FACTOR = 'SET_DILUTION_FACTOR';
export const SET_TEMPLATE_PLATE = 'SET_TEMPLATE_PLATE';
export const SET_HGDNA_PLATE = 'SET_HGDNA_PLATE';
export const SET_DILUTION_PLATE = 'SET_DILUTION_PLATE';
