export const SET_VALID_OBJECTS = 'SET_VALID_OBJECTS';
export const SET_INVALID_OBJECTS = 'SET_INVALID_OBJECTS';
export const SET_ERROR_MESSAGES = 'SET_ERROR_MESSAGES';
export const SET_PARSED_PLATE = 'SET_PARSED_PLATE';
