export const ADJUST_TOOL_TIP_POSITION = 'ADJUST_TOOL_TIP_POSITION';
export const SHOW_BLUR = 'SHOW_BLUR';
export const SHOW_SUGGESTIONS_TOOL_TIP = 'SHOW_SUGGESTIONS_TOOL_TIP';
export const SHOW_SUGGESTIONS_LIST = 'SHOW_SUGGESTIONS_LIST';
export const SHOW_WELL_CONTENTS = 'SHOW_WELL_CONTENTS';
export const SHOW_INFO = 'SHOW_INFO';
export const HIGHLIGHT_HOVER = 'HIGHLIGHT_HOVER';
