export const REQUEST_AVAILABLE_SUGGESTIONS = 'REQUEST_AVAILABLE_SUGGESTIONS';
export const RECEIVED_AVAILABLE_SUGGESTIONS = 'RECEIVED_AVAILABLE_SUGGESTIONS';
export const AVAILABLE_SUGGESTIONS_FAILURE = 'AVAILABLE_SUGGESTIONS_FAILURE';
export const SAVE_SUGGESTIONS = 'SAVE_SUGGESTIONS';
