export const REQUEST_AVAILABLE_REAGENT_GROUPS = 'REQUEST_AVAILABLE_REAGENT_GROUPS';
export const RECEIVED_AVAILABLE_REAGENT_GROUPS = 'RECEIVED_AVAILABLE_REAGENT_GROUPS';
export const AVAILABLE_REAGENT_GROUPS_FAILURE = 'AVAILABLE_REAGENT_GROUPS_FAILURE';

